// Company data
export const companies = [
    { name: 'Accenture', logo: 'accenture.jpg' },
    { name: 'Adaptive Insights', logo: 'adaptiveinsights.jpg' },
    { name: 'Addepar', logo: 'Addepar.png' },
    { name: 'Adobe', logo: 'Adobe.png' },
    { name: 'Allegiant Air', logo: 'Allegiant-Air.jpg' },
    { name: 'Amazon', logo: 'amazon.jpg' },
    { name: 'Apple', logo: 'apple.jpg' },
    { name: 'Applied Materials', logo: 'Applied-Materials.jpg' },
    { name: 'BetterHelp', logo: 'BetterHelp.png' },
    { name: 'Blach', logo: 'blach.jpg' },
    { name: 'Buf', logo: 'Buf.png' },
    { name: 'Chime', logo: 'Chime.png' },
    { name: 'Cisco', logo: 'Cisco_Logo.jpg' },
    { name: 'Citi', logo: 'Citi.png' },
    { name: 'CloudMed', logo: 'Cloudmed.png' },
    { name: 'Coupa', logo: 'Coupa.png' },
    { name: 'CrowdStrike', logo: 'CrowdStrike.png' },
    { name: 'CueBack', logo: 'CueBack.png' },
    { name: 'Deloitte', logo: 'deloitte-logo.jpg' },
    { name: 'Dolby', logo: 'dolby.jpg' },
    { name: 'EY', logo: 'EY.jpg' },
    { name: 'Fanatics', logo: 'Fanatics.png' },
    { name: 'Fast Enterprises', logo: 'FastEnterprises.png' },
    { name: 'FireEye', logo: 'fireeye.jpg' },
    { name: 'First Republic Bank', logo: 'FirstRepublicBank.png' },
    { name: 'Flextronics', logo: 'Flextronics.jpg' },
    { name: 'Gap', logo: 'gap.jpg' },
    { name: 'Google', logo: 'google.jpg' },
    { name: 'Hitachi', logo: 'hitachi.jpg' },
    { name: 'Hive', logo: 'Hive.png' },
    { name: 'Imprivata', logo: 'Imprivata.jpg' },
    { name: 'Intel', logo: 'intel.jpg' },
    { name: 'Intuitive Surgical', logo: 'intuitivesurgical.jpg' },
    { name: 'JP Morgan Chase', logo: 'JP-Morgan-Chase-Emblem.jpg' },
    { name: 'Juniper', logo: 'juniper.jpg' },
    { name: 'KPMG', logo: 'kpmg.jpg' },
    { name: 'Lexi"s AI', logo: 'LexisAI.svg' },
    { name: 'Liberty Mutual', logo: 'LibertyMutual.png' },
    { name: 'LinkedIn', logo: 'linkedin.jpg' },
    { name: 'Mercedes-Benz', logo: 'Mercedes-Benz.jpg' },
    { name: 'Morgan Stanley', logo: 'MorganStanley.png' },
    { name: 'Murphy Cordier Casale Axel', logo: 'MurphyCordierCasaleAxel.png' },
    { name: 'NBCUniversal', logo: 'NBCUniversal.jpg' },
    { name: 'Net Impact', logo: 'netimpact.jpg' },
    { name: 'NetApp', logo: 'netap.jpg' },
    { name: 'Nordstrom', logo: 'Nordstrom.png' },
    { name: 'NOVO Brazil Brewing', logo: 'NOVOBrazilBrewing.png' },
    { name: 'Olympus Controls', logo: 'OlympusControls.png' },
    { name: 'OMD', logo: 'OMD.png' },
    { name: 'Onerent', logo: 'onerent.jpg' },
    { name: 'Oracle', logo: 'Oracle.jpg' },
    { name: 'Palo Alto Networks', logo: 'PaloAltoNetworks.png' },
    { name: 'Pottery Barn', logo: 'PotteryBarn.jpg' },
    { name: 'Presidio Bank', logo: 'presidiobank.jpg' },
    { name: 'PwC', logo: 'pwc.jpg' },
    { name: 'RBC', logo: 'RBC.png' },
    { name: 'Rematch', logo: 'Rematch.png' },
    { name: 'Salesforce', logo: 'salesforce.jpg' },
    { name: 'Sephora', logo: 'Sephora.png' },
    { name: 'SMB Capital', logo: 'SMBCapital.png' },
    { name: 'Snowflake', logo: 'snow.jpg' },
    { name: 'Splunk', logo: 'Splunk.png' },
    { name: 'Target', logo: 'target.jpg' },
    { name: 'Tesla', logo: 'tesla.jpg' },
    { name: 'TTEC', logo: 'TTEC.png' },
    { name: 'Tufts Medical', logo: 'TuftsMed.png' },
    { name: 'Twitch', logo: 'Twitch.png' },
    { name: 'Tyler Technologies', logo: 'TylerTechnologies.png' },
    { name: 'Unum', logo: 'Unum.png' },
    { name: 'Visa', logo: 'visas.jpg' },
    { name: 'VMware', logo: 'vmware.jpg' },
    { name: 'Walmart', logo: 'walmart.jpg' },
    { name: 'WSP', logo: 'WSP.png' },
    { name: 'Yahoo', logo: 'Yahoo_3.jpg' },
    { name: 'Yelp', logo: 'yelp.jpg' },
    { name: 'Zappos', logo: 'Zappos.jpg' },
    { name: 'Zwift', logo: 'Zwift.png' },
];
